plugins {
	id 'java'
}

group = 'com.chunkboomerits'
version = '1.4.1'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
	maven {
		name = 'papermc'
		url = 'https://repo.papermc.io/repository/maven-public/'
	}
}

dependencies {
	compileOnly 'io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT'
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
	options.release = 21
}

processResources {
	def props = [version: version]
	inputs.properties props
	filesMatching('plugin.yml') {
		expand props
	}
}

tasks.register('zipResourcePack', Zip) {
	archiveFileName = 'ChunkBoomerits-RP.zip'
	destinationDirectory = layout.projectDirectory.dir('src/main/resources')
	from(rootProject.file('../resourcepack')) {
		into '/'
	}
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

processResources.dependsOn(zipResourcePack)

jar {
	archiveBaseName.set('ChunkBoomerits')
	archiveVersion.set(version)
	dependsOn(zipResourcePack)
}
